esphome:
  name: clock-bme280
  friendly_name: clock-bme280

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "INSERT API KEY"

ota:
  password: "INSERT PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Clock Fallback Hotspot"
    password: "CREATE SSID PASSWORD"
i2c:
  sda: D2
  scl: D1
  scan: False
  
# Example configuration entry
sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280-1 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280-1 Pressure"
    humidity:
      name: "BME280-1 Humidity"
    # Address is not default!
    address: 0x76
    update_interval: 60s

time:
  - platform: homeassistant
    id: homeassistant_time

display:
  platform: tm1637
  clk_pin: D3
  dio_pin: D4
  intensity: 0
  length: 4
  update_interval: 500ms
  lambda: |-
      static int i = 0;
      i++;
      if ((i % 2) == 0)
        it.strftime("%H.%M", id(homeassistant_time).now());
      else
        it.strftime("%H%M", id(homeassistant_time).now());

captive_portal:
    